/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cclip.gui.aacc;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cclip.gui.JFrameMainGui;
import com.cclip.gui.util.JLabelTimer;
import com.cclip.model.person.UserSystem;
import com.cclip.services.Services;

/**
 *
 * @author java
 */
public class JDialogImportIceDbProgress extends javax.swing.JDialog implements ActionListener {

	private UserSystem userSystem;
	private File unidad;
	private File inmueble;
	private File superficie;
	private File subcuenta;
	private File datosPostales;

	/**
	 * Creates new form JDialogInmAddress
	 * 
	 * @throws Exception
	 */
	public JDialogImportIceDbProgress(JFrame jframe, UserSystem userSystem, File unidad, File inmueble, File superficie, File subcuenta, File datosPostales) throws Exception {
		super(jframe);
		initComponents();

		jButtonCancel.setIcon(new ImageIcon(JFrameMainGui.iconPath + "application-exit.png"));
		jButtonStart.setIcon(new ImageIcon(JFrameMainGui.iconPath + "run-build.png"));
		jButtonStop.setIcon(new ImageIcon(JFrameMainGui.iconPath + "user-busy.png"));

		// jLabelTimer1 = new JLabelTimer();
		// jLabelTimer2 = new JLabelTimer();
		// jLabelTimer3 = new JLabelTimer();
		// jLabelTimer4 = new JLabelTimer();
		// jLabelTimer5 = new JLabelTimer();
		// jLabelTimer6 = new JLabelTimer();
		// jLabelTimer7 = new JLabelTimer();
		// jLabelTimer8 = new JLabelTimer();
		// jLabelTimer9 = new JLabelTimer();

		// public JLabelTimer jLabelTimer;
		// public JLabelTimer jLabelTimer1;
		// public JLabelTimer jLabelTimer10;
		// public JLabelTimer jLabelTimer2;
		// public JLabelTimer jLabelTimer3;
		// public JLabelTimer jLabelTimer4;
		// public JLabelTimer jLabelTimer5;
		// public JLabelTimer jLabelTimer6;
		// public JLabelTimer jLabelTimer7;
		// public JLabelTimer jLabelTimer8;
		// public JLabelTimer jLabelTimer9;

		setSize(1461, 689);

		Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
		int x = (int) ((dimension.getWidth() - 1461) / 2);
		int y = (int) ((dimension.getHeight() - 689) / 2);
		setLocation(x, y);
		jButtonCancel.addActionListener(this);
		jButtonStart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				start();
			}
		});
		jButtonStop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stop();
			}
		});

		this.userSystem = userSystem;
		this.unidad = unidad;
		this.inmueble = inmueble;
		this.superficie = superficie;
		this.subcuenta = subcuenta;
		this.datosPostales = datosPostales;

		jButtonStart.setVisible(true);
		jButtonStop.setVisible(false);
		jButtonCancel.setVisible(true);

		pack();

		setVisible(true);

	}

	public void actionPerformed(ActionEvent e) {
		setVisible(false);
		dispose();
	}

	public void stop() {
		Services.getInstance().importUnl.stop();

	}

	public void start() {

		Object[] options = { "Si", "No" };
		int choice = JOptionPane.showOptionDialog(this, "Esta operación puede llevar un tiempo considerado. ¿ Esta seguro de proseguir ? ", "¿ Importar Base de Datos Congelada ?",
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon((JFrameMainGui.iconPath + "user-busy.png")), options, options[1]);

		if (choice == JOptionPane.YES_OPTION) {

			Services.getInstance().importUnl.setUserSystem(userSystem);
			Services.getInstance().importUnl.setGui(this);
			Services.getInstance().importUnl.setUnidad(unidad);
			Services.getInstance().importUnl.setInmueble(inmueble);
			Services.getInstance().importUnl.setSuperficie(superficie);
			Services.getInstance().importUnl.setSubcuenta(subcuenta);
			Services.getInstance().importUnl.setDatosPostales(datosPostales);

			Services.getInstance().importUnl.execute();

			jButtonStart.setVisible(false);
			jButtonStop.setVisible(true);
			jButtonCancel.setVisible(false);

		} else {
			jButtonStart.setVisible(true);
			jButtonStop.setVisible(false);
			jButtonCancel.setVisible(true);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel4 = new javax.swing.JPanel();
		jButtonStart = new javax.swing.JButton();
		jButtonStop = new javax.swing.JButton();
		jLabelStart = new javax.swing.JLabel();
		jLabelStartValue = new javax.swing.JLabel();
		jLabelEndValue = new javax.swing.JLabel();
		jLabelEnd = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		jCheckBox2 = new javax.swing.JCheckBox();
		jLabel2 = new javax.swing.JLabel();
		jCheckBox3 = new javax.swing.JCheckBox();
		jLabel3 = new javax.swing.JLabel();
		jCheckBox4 = new javax.swing.JCheckBox();
		jLabel4 = new javax.swing.JLabel();
		jCheckBox5 = new javax.swing.JCheckBox();
		jLabel5 = new javax.swing.JLabel();
		jCheckBox6 = new javax.swing.JCheckBox();
		jLabel6 = new javax.swing.JLabel();
		jCheckBox7 = new javax.swing.JCheckBox();
		jLabel7 = new javax.swing.JLabel();
		jCheckBox8 = new javax.swing.JCheckBox();
		jLabel8 = new javax.swing.JLabel();
		jCheckBox9 = new javax.swing.JCheckBox();
		jLabel9 = new javax.swing.JLabel();
		jProgressBar1 = new javax.swing.JProgressBar();
		jProgressBar2 = new javax.swing.JProgressBar();
		jProgressBar3 = new javax.swing.JProgressBar();
		jProgressBar4 = new javax.swing.JProgressBar();
		jProgressBar5 = new javax.swing.JProgressBar();
		jProgressBar6 = new javax.swing.JProgressBar();
		jProgressBar7 = new javax.swing.JProgressBar();
		jProgressBar9 = new javax.swing.JProgressBar();
		jProgressBar8 = new javax.swing.JProgressBar();
		jLabel9_1 = new javax.swing.JLabel();
		jLabel8_1 = new javax.swing.JLabel();
		jLabel7_1 = new javax.swing.JLabel();
		jLabel6_1 = new javax.swing.JLabel();
		jLabel5_1 = new javax.swing.JLabel();
		jLabelTimer1 = new JLabelTimer();
		jLabelTimer2 = new JLabelTimer();
		jLabelTimer3 = new JLabelTimer();
		jLabelTimer4 = new JLabelTimer();
		jLabelTimer5 = new JLabelTimer();
		jLabelTimer6 = new JLabelTimer();
		jLabelTimer7 = new JLabelTimer();
		jLabelTimer8 = new JLabelTimer();
		jLabelTimer9 = new JLabelTimer();
		jPanel2 = new javax.swing.JPanel();
		jCheckBox10 = new javax.swing.JCheckBox();
		jLabel10 = new javax.swing.JLabel();
		jProgressBar10 = new javax.swing.JProgressBar();
		jLabelTimer10 = new JLabelTimer();
		jLabel10_1 = new javax.swing.JLabel();
		jProgressBar11 = new javax.swing.JProgressBar();
		jLabelTimer11 = new JLabelTimer();
		jCheckBox11 = new javax.swing.JCheckBox();
		jLabel11 = new javax.swing.JLabel();
		jLabel11_1 = new javax.swing.JLabel();
		jProgressBar12 = new javax.swing.JProgressBar();
		jLabelTimer12 = new JLabelTimer();
		jCheckBox12 = new javax.swing.JCheckBox();
		jLabel12 = new javax.swing.JLabel();
		jLabel12_1 = new javax.swing.JLabel();
		jProgressBar13 = new javax.swing.JProgressBar();
		jLabelTimer13 = new JLabelTimer();
		jCheckBox13 = new javax.swing.JCheckBox();
		jLabel13 = new javax.swing.JLabel();
		jLabel13_1 = new javax.swing.JLabel();
		jProgressBar14 = new javax.swing.JProgressBar();
		jLabelTimer14 = new JLabelTimer();
		jCheckBox14 = new javax.swing.JCheckBox();
		jLabel14 = new javax.swing.JLabel();
		jLabel14_1 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jCheckBox15 = new javax.swing.JCheckBox();
		jProgressBar15 = new javax.swing.JProgressBar();
		jLabelTimer15 = new JLabelTimer();
		jProgressBar16 = new javax.swing.JProgressBar();
		jLabelTimer16 = new JLabelTimer();
		jCheckBox16 = new javax.swing.JCheckBox();
		jProgressBar17 = new javax.swing.JProgressBar();
		jLabelTimer17 = new JLabelTimer();
		jCheckBox17 = new javax.swing.JCheckBox();
		jProgressBar18 = new javax.swing.JProgressBar();
		jLabelTimer18 = new JLabelTimer();
		jCheckBox18 = new javax.swing.JCheckBox();
		jProgressBar19 = new javax.swing.JProgressBar();
		jLabelTimer19 = new JLabelTimer();
		jCheckBox19 = new javax.swing.JCheckBox();
		jProgressBar20 = new javax.swing.JProgressBar();
		jLabelTimer20 = new JLabelTimer();
		jCheckBox20 = new javax.swing.JCheckBox();
		jProgressBar21 = new javax.swing.JProgressBar();
		jLabelTimer21 = new JLabelTimer();
		jCheckBox21 = new javax.swing.JCheckBox();
		jProgressBar22 = new javax.swing.JProgressBar();
		jLabelTimer22 = new JLabelTimer();
		jCheckBox22 = new javax.swing.JCheckBox();
		jProgressBar23 = new javax.swing.JProgressBar();
		jLabelTimer23 = new JLabelTimer();
		jCheckBox23 = new javax.swing.JCheckBox();
		jProgressBar24 = new javax.swing.JProgressBar();
		jLabelTimer24 = new JLabelTimer();
		jCheckBox24 = new javax.swing.JCheckBox();
		jProgressBar25 = new javax.swing.JProgressBar();
		jLabelTimer25 = new JLabelTimer();
		jCheckBox25 = new javax.swing.JCheckBox();
		jProgressBar26 = new javax.swing.JProgressBar();
		jLabelTimer26 = new JLabelTimer();
		jCheckBox26 = new javax.swing.JCheckBox();
		jProgressBar27 = new javax.swing.JProgressBar();
		jLabelTimer27 = new JLabelTimer();
		jCheckBox27 = new javax.swing.JCheckBox();
		jProgressBar28 = new javax.swing.JProgressBar();
		jLabelTimer28 = new JLabelTimer();
		jCheckBox28 = new javax.swing.JCheckBox();
		jProgressBar29 = new javax.swing.JProgressBar();
		jLabelTimer29 = new JLabelTimer();
		jCheckBox29 = new javax.swing.JCheckBox();
		jProgressBar = new javax.swing.JProgressBar();
		jButtonCancel = new javax.swing.JButton();
		jLabelTimer = new JLabelTimer();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Domicilio del Inmueble");
		setModal(true);
		setUndecorated(true);
		setResizable(false);

		jPanel4.setBackground(new java.awt.Color(0, 102, 153));
		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), "Importando Base Congelada",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
		jPanel4.setForeground(new java.awt.Color(0, 102, 153));

		jButtonStart.setText("Start");

		jButtonStop.setText("Stop");

		jLabelStart.setBackground(new java.awt.Color(255, 255, 255));
		jLabelStart.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelStart.setForeground(new java.awt.Color(255, 255, 255));
		jLabelStart.setText("Fecha y hora de inicio: ");

		jLabelStartValue.setBackground(new java.awt.Color(255, 255, 255));
		jLabelStartValue.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabelStartValue.setForeground(new java.awt.Color(255, 255, 255));
		jLabelStartValue.setText("Fecha y hora de inicio: ");

		jLabelEndValue.setBackground(new java.awt.Color(255, 255, 255));
		jLabelEndValue.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabelEndValue.setForeground(new java.awt.Color(255, 255, 255));
		jLabelEndValue.setText("Fecha y hora de inicio: ");

		jLabelEnd.setBackground(new java.awt.Color(255, 255, 255));
		jLabelEnd.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelEnd.setForeground(new java.awt.Color(255, 255, 255));
		jLabelEnd.setText("Fecha y hora de inicio: ");

		jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

		jPanel1.setBackground(new java.awt.Color(0, 102, 153));

		jCheckBox1.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox1.setText("1 - Crear carpeta principal de trabajo:");
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("ruta del archivo");

		jCheckBox2.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox2.setText("2 - Crear carpeta de trabajo de pre import:");
		jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox2ActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("ruta del archivo");

		jCheckBox3.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox3.setText("3 - Crear carpeta de trabajo de post import:");
		jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox3ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("ruta del archivo");

		jCheckBox4.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox4.setText("4 - Crear carpeta de trabajo de pre import Batch:");
		jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox4ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("ruta del archivo");

		jCheckBox5.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox5.setText("5 - Copiar archivo unidad a pre import Batch:");
		jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox5ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("ruta del archivo");

		jCheckBox6.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox6.setText("6 - Copiar archivo inmueble a pre import Batch:");
		jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox6ActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("ruta del archivo");

		jCheckBox7.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox7.setText("7 - Copiar archivo superficie a pre import Batch:");
		jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox7ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("ruta del archivo");

		jCheckBox8.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox8.setText("8 - Copiar archivo subcuenta a pre import Batch:");
		jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox8ActionPerformed(evt);
			}
		});

		jLabel8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("ruta del archivo");

		jCheckBox9.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox9.setText("9 - Copiar archivo datos postales a pre import Batch:");
		jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox9ActionPerformed(evt);
			}
		});

		jLabel9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("ruta del archivo");

		jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar1.setStringPainted(true);

		jProgressBar2.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar2.setStringPainted(true);

		jProgressBar3.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar3.setStringPainted(true);

		jProgressBar4.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar4.setStringPainted(true);

		jProgressBar5.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar5.setStringPainted(true);

		jProgressBar6.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar6.setStringPainted(true);

		jProgressBar7.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar7.setStringPainted(true);

		jProgressBar9.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar9.setStringPainted(true);

		jProgressBar8.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar8.setStringPainted(true);

		jLabel9_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel9_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9_1.setText("ruta del archivo");

		jLabel8_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel8_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8_1.setText("ruta del archivo");

		jLabel7_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel7_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7_1.setText("ruta del archivo");

		jLabel6_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel6_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6_1.setText("ruta del archivo");

		jLabel5_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel5_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5_1.setText("ruta del archivo");

		jLabelTimer1.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer1.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer1.setText("00:00:00");

		jLabelTimer2.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer2.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer2.setText("00:00:00");

		jLabelTimer3.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer3.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer3.setText("00:00:00");

		jLabelTimer4.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer4.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer4.setText("00:00:00");

		jLabelTimer5.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer5.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer5.setText("00:00:00");

		jLabelTimer6.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer6.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer6.setText("00:00:00");

		jLabelTimer7.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer7.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer7.setText("00:00:00");

		jLabelTimer8.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer8.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer8.setText("00:00:00");

		jLabelTimer9.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer9.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer9.setText("00:00:00");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.CENTER,
						jPanel1Layout
								.createSequentialGroup()
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel5_1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel6, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel6_1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel7, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel7_1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel8_1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel9, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jLabel9_1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)).addGap(1127, 1127, 1127))
				.addGroup(
						jPanel1Layout
								.createSequentialGroup()
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addGroup(
																		jPanel1Layout
																				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabelTimer2)
																				.addComponent(jLabelTimer1))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jCheckBox1).addComponent(jCheckBox2)
																				.addComponent(jCheckBox3).addComponent(jCheckBox4).addComponent(jCheckBox5).addComponent(jCheckBox6)
																				.addComponent(jCheckBox7).addComponent(jCheckBox8).addComponent(jCheckBox9)))
												.addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addGap(160, 160, 160)
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabelTimer9)
																				.addComponent(jLabelTimer8).addComponent(jLabelTimer7).addComponent(jLabelTimer6).addComponent(jLabelTimer5)
																				.addComponent(jLabelTimer4).addComponent(jLabelTimer3))))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel1)
						.addGap(5, 5, 5)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox2))
						.addGap(5, 5, 5)
						.addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox3))
						.addGap(5, 5, 5)
						.addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox4))
						.addGap(3, 3, 3)
						.addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox5))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel5)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel5_1)
						.addGap(5, 5, 5)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox6))
						.addGap(3, 3, 3)
						.addComponent(jLabel6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel6_1)
						.addGap(9, 9, 9)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox7))
						.addGap(3, 3, 3)
						.addComponent(jLabel7)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel7_1)
						.addGap(10, 10, 10)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox8))
						.addGap(3, 3, 3)
						.addComponent(jLabel8)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel8_1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox9)).addGap(3, 3, 3)
						.addComponent(jLabel9).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel9_1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jTabbedPane1.addTab("A", jPanel1);

		jPanel2.setBackground(new java.awt.Color(0, 102, 153));

		jCheckBox10.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox10.setText("10 - Tabla cclip.aacc_unidad");
		jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox10ActionPerformed(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("ruta del archivo");

		jProgressBar10.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar10.setStringPainted(true);

		jLabelTimer10.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer10.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer10.setText("00:00:00");

		jLabel10_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel10_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10_1.setText("ruta del archivo");

		jProgressBar11.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar11.setStringPainted(true);

		jLabelTimer11.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer11.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer11.setText("00:00:00");

		jCheckBox11.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox11.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox11.setText("11 - Tabla cclip.aacc_inmueble");
		jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox11ActionPerformed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("ruta del archivo");

		jLabel11_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel11_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11_1.setText("ruta del archivo");

		jProgressBar12.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar12.setStringPainted(true);

		jLabelTimer12.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer12.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer12.setText("00:00:00");

		jCheckBox12.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox12.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox12.setText("12 - Tabla cclip.aacc_superficie");
		jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox12ActionPerformed(evt);
			}
		});

		jLabel12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("ruta del archivo");

		jLabel12_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel12_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12_1.setText("ruta del archivo");

		jProgressBar13.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar13.setStringPainted(true);

		jLabelTimer13.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer13.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer13.setText("00:00:00");

		jCheckBox13.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox13.setText("13 - Tabla cclip.aacc_subcuenta");
		jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox13ActionPerformed(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("ruta del archivo");

		jLabel13_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel13_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13_1.setText("ruta del archivo");

		jProgressBar14.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar14.setStringPainted(true);

		jLabelTimer14.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer14.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer14.setText("00:00:00");

		jCheckBox14.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox14.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox14.setText("14 - Tabla cclip.aacc_datos_postales");
		jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox14ActionPerformed(evt);
			}
		});

		jLabel14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("ruta del archivo");

		jLabel14_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
		jLabel14_1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14_1.setText("ruta del archivo");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.CENTER,
						jPanel2Layout.createSequentialGroup().addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGap(1127, 1127, 1127))
				.addGroup(
						jPanel2Layout
								.createSequentialGroup()
								.addGroup(
										jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														jPanel2Layout
																.createSequentialGroup()
																.addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabelTimer10).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox10))
												.addComponent(jLabel10_1)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(
						jPanel2Layout
								.createSequentialGroup()
								.addGroup(
										jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.CENTER,
														jPanel2Layout.createSequentialGroup()
																.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addGap(324, 324, 324))
												.addGroup(
														jPanel2Layout
																.createSequentialGroup()
																.addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabelTimer11).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox11))
												.addComponent(jLabel11_1)
												.addGroup(
														jPanel2Layout
																.createSequentialGroup()
																.addComponent(jProgressBar12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabelTimer12).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox12))
												.addGroup(
														jPanel2Layout
																.createSequentialGroup()
																.addComponent(jProgressBar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabelTimer13).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox13))
												.addGroup(
														jPanel2Layout
																.createSequentialGroup()
																.addComponent(jProgressBar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabelTimer14).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox14))
												.addGroup(
														jPanel2Layout
																.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(jLabel12_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(
														jPanel2Layout
																.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(jLabel13_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(
														jPanel2Layout
																.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(jLabel14_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox10))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel10)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel10_1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox11))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel11)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel11_1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox12))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel12)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel12_1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox13))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel13)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel13_1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox14))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel14).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel14_1).addContainerGap(191, Short.MAX_VALUE)));

		jTabbedPane1.addTab("B", jPanel2);

		jPanel3.setBackground(new java.awt.Color(0, 102, 153));

		jCheckBox15.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox15.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox15.setText("15 - Tabla aacc_superficie_new_case");
		jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox15ActionPerformed(evt);
			}
		});

		jProgressBar15.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar15.setStringPainted(true);

		jLabelTimer15.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer15.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer15.setText("00:00:00");

		jProgressBar16.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar16.setStringPainted(true);

		jLabelTimer16.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer16.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer16.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer16.setText("00:00:00");

		jCheckBox16.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox16.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox16.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox16.setText("16");
		jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox16ActionPerformed(evt);
			}
		});

		jProgressBar17.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar17.setStringPainted(true);

		jLabelTimer17.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer17.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer17.setText("00:00:00");

		jCheckBox17.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox17.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox17.setText("17");
		jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox17ActionPerformed(evt);
			}
		});

		jProgressBar18.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar18.setStringPainted(true);

		jLabelTimer18.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer18.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer18.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer18.setText("00:00:00");

		jCheckBox18.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox18.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox18.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox18.setText("18");
		jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox18ActionPerformed(evt);
			}
		});

		jProgressBar19.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar19.setStringPainted(true);

		jLabelTimer19.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer19.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer19.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer19.setText("00:00:00");

		jCheckBox19.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox19.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox19.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox19.setText("19");
		jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox19ActionPerformed(evt);
			}
		});

		jProgressBar20.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar20.setStringPainted(true);

		jLabelTimer20.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer20.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer20.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer20.setText("00:00:00");

		jCheckBox20.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox20.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox20.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox20.setText("20");
		jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox20ActionPerformed(evt);
			}
		});

		jProgressBar21.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar21.setStringPainted(true);

		jLabelTimer21.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer21.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer21.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer21.setText("00:00:00");

		jCheckBox21.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox21.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox21.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox21.setText("21");
		jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox21ActionPerformed(evt);
			}
		});

		jProgressBar22.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar22.setStringPainted(true);

		jLabelTimer22.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer22.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer22.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer22.setText("00:00:00");

		jCheckBox22.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox22.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox22.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox22.setText("22");
		jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox22ActionPerformed(evt);
			}
		});

		jProgressBar23.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar23.setStringPainted(true);

		jLabelTimer23.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer23.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer23.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer23.setText("00:00:00");

		jCheckBox23.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox23.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox23.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox23.setText("23");
		jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox23ActionPerformed(evt);
			}
		});

		jProgressBar24.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar24.setStringPainted(true);

		jLabelTimer24.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer24.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer24.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer24.setText("00:00:00");

		jCheckBox24.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox24.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox24.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox24.setText("24");
		jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox24ActionPerformed(evt);
			}
		});

		jProgressBar25.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar25.setStringPainted(true);

		jLabelTimer25.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer25.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer25.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer25.setText("00:00:00");

		jCheckBox25.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox25.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox25.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox25.setText("25");
		jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox25ActionPerformed(evt);
			}
		});

		jProgressBar26.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar26.setStringPainted(true);

		jLabelTimer26.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer26.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer26.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer26.setText("00:00:00");

		jCheckBox26.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox26.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox26.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox26.setText("26");
		jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox26ActionPerformed(evt);
			}
		});

		jProgressBar27.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar27.setStringPainted(true);

		jLabelTimer27.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer27.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer27.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer27.setText("00:00:00");

		jCheckBox27.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox27.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox27.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox27.setText("27");
		jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox27ActionPerformed(evt);
			}
		});

		jProgressBar28.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar28.setStringPainted(true);

		jLabelTimer28.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer28.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer28.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer28.setText("00:00:00");

		jCheckBox28.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox28.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox28.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox28.setText("28");
		jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox28ActionPerformed(evt);
			}
		});

		jProgressBar29.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar29.setStringPainted(true);

		jLabelTimer29.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer29.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jLabelTimer29.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer29.setText("00:00:00");

		jCheckBox29.setBackground(new java.awt.Color(0, 102, 153));
		jCheckBox29.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
		jCheckBox29.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox29.setText("29");
		jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox29ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout
						.createSequentialGroup()
						.addGroup(
								jPanel3Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(
												jPanel3Layout
														.createSequentialGroup()
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
																		.addComponent(jProgressBar15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jLabelTimer20).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jCheckBox20))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabelTimer16)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox16))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabelTimer19)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox19))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabelTimer18)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox18))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jLabelTimer21).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jCheckBox21))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabelTimer17)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox17))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jLabelTimer22).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jCheckBox22))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabelTimer15)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox15))))
										.addGroup(
												jPanel3Layout
														.createSequentialGroup()
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
																		.addComponent(jProgressBar26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addComponent(jLabelTimer26)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox26))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addComponent(jLabelTimer25)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox25))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addComponent(jLabelTimer27)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox27))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addComponent(jLabelTimer28)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox28))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addComponent(jLabelTimer24)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox24))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addComponent(jLabelTimer29)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox29))
																		.addGroup(
																				jPanel3Layout.createSequentialGroup().addComponent(jLabelTimer23)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox23)))
														.addGap(189, 189, 189))
										.addGroup(
												javax.swing.GroupLayout.Alignment.CENTER,
												jPanel3Layout
														.createSequentialGroup()
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(jProgressBar20, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar21, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar19, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar18, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar17, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jProgressBar22, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(298, 298, 298)))
						.addContainerGap(756, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox15))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox16))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox17))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox18))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox19))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox20))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox21))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox22))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox23))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox24))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox25))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox26))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox27))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox28))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox29))
						.addContainerGap(95, Short.MAX_VALUE)));

		jTabbedPane1.addTab("C", jPanel3);

		jProgressBar.setBackground(new java.awt.Color(255, 255, 255));
		jProgressBar.setStringPainted(true);

		jButtonCancel.setText("Salir");
		jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		jLabelTimer.setBackground(new java.awt.Color(255, 255, 255));
		jLabelTimer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		jLabelTimer.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTimer.setText("00:00:00");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jTabbedPane1)
				.addGroup(
						jPanel4Layout
								.createSequentialGroup()
								.addGroup(
										jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														jPanel4Layout.createSequentialGroup().addComponent(jLabelStart).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabelStartValue).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabelEnd)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabelEndValue)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabelTimer)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButtonStart).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButtonStop).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jButtonCancel).addGap(0, 0, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout
						.createSequentialGroup()
						.addGroup(
								jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
										.addComponent(jLabelStart, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelStartValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelEndValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButtonStart).addComponent(jButtonStop)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
						.addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButtonCancel)));

		jTabbedPane1.getAccessibleContext().setAccessibleName("A");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox29ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	public javax.swing.JButton jButtonCancel;
	public javax.swing.JButton jButtonStart;
	public javax.swing.JButton jButtonStop;
	public javax.swing.JCheckBox jCheckBox1;
	public javax.swing.JCheckBox jCheckBox10;
	public javax.swing.JCheckBox jCheckBox11;
	public javax.swing.JCheckBox jCheckBox12;
	public javax.swing.JCheckBox jCheckBox13;
	public javax.swing.JCheckBox jCheckBox14;
	public javax.swing.JCheckBox jCheckBox15;
	public javax.swing.JCheckBox jCheckBox16;
	public javax.swing.JCheckBox jCheckBox17;
	public javax.swing.JCheckBox jCheckBox18;
	public javax.swing.JCheckBox jCheckBox19;
	public javax.swing.JCheckBox jCheckBox2;
	public javax.swing.JCheckBox jCheckBox20;
	public javax.swing.JCheckBox jCheckBox21;
	public javax.swing.JCheckBox jCheckBox22;
	public javax.swing.JCheckBox jCheckBox23;
	public javax.swing.JCheckBox jCheckBox24;
	public javax.swing.JCheckBox jCheckBox25;
	public javax.swing.JCheckBox jCheckBox26;
	public javax.swing.JCheckBox jCheckBox27;
	public javax.swing.JCheckBox jCheckBox28;
	public javax.swing.JCheckBox jCheckBox29;
	public javax.swing.JCheckBox jCheckBox3;
	public javax.swing.JCheckBox jCheckBox4;
	public javax.swing.JCheckBox jCheckBox5;
	public javax.swing.JCheckBox jCheckBox6;
	public javax.swing.JCheckBox jCheckBox7;
	public javax.swing.JCheckBox jCheckBox8;
	public javax.swing.JCheckBox jCheckBox9;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabel10;
	public javax.swing.JLabel jLabel10_1;
	public javax.swing.JLabel jLabel11;
	public javax.swing.JLabel jLabel11_1;
	public javax.swing.JLabel jLabel12;
	public javax.swing.JLabel jLabel12_1;
	public javax.swing.JLabel jLabel13;
	public javax.swing.JLabel jLabel13_1;
	public javax.swing.JLabel jLabel14;
	public javax.swing.JLabel jLabel14_1;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JLabel jLabel3;
	public javax.swing.JLabel jLabel4;
	public javax.swing.JLabel jLabel5;
	public javax.swing.JLabel jLabel5_1;
	public javax.swing.JLabel jLabel6;
	public javax.swing.JLabel jLabel6_1;
	public javax.swing.JLabel jLabel7;
	public javax.swing.JLabel jLabel7_1;
	public javax.swing.JLabel jLabel8;
	public javax.swing.JLabel jLabel8_1;
	public javax.swing.JLabel jLabel9;
	public javax.swing.JLabel jLabel9_1;
	protected javax.swing.JLabel jLabelEnd;
	public javax.swing.JLabel jLabelEndValue;
	protected javax.swing.JLabel jLabelStart;
	public javax.swing.JLabel jLabelStartValue;
	public JLabelTimer jLabelTimer;
	public JLabelTimer jLabelTimer1;
	public JLabelTimer jLabelTimer10;
	public JLabelTimer jLabelTimer11;
	public JLabelTimer jLabelTimer12;
	public JLabelTimer jLabelTimer13;
	public JLabelTimer jLabelTimer14;
	public JLabelTimer jLabelTimer15;
	public JLabelTimer jLabelTimer16;
	public JLabelTimer jLabelTimer17;
	public JLabelTimer jLabelTimer18;
	public JLabelTimer jLabelTimer19;
	public JLabelTimer jLabelTimer2;
	public JLabelTimer jLabelTimer20;
	public JLabelTimer jLabelTimer21;
	public JLabelTimer jLabelTimer22;
	public JLabelTimer jLabelTimer23;
	public JLabelTimer jLabelTimer24;
	public JLabelTimer jLabelTimer25;
	public JLabelTimer jLabelTimer26;
	public JLabelTimer jLabelTimer27;
	public JLabelTimer jLabelTimer28;
	public JLabelTimer jLabelTimer29;
	public JLabelTimer jLabelTimer3;
	public JLabelTimer jLabelTimer4;
	public JLabelTimer jLabelTimer5;
	public JLabelTimer jLabelTimer6;
	public JLabelTimer jLabelTimer7;
	public JLabelTimer jLabelTimer8;
	public JLabelTimer jLabelTimer9;
	public javax.swing.JPanel jPanel1;
	public javax.swing.JPanel jPanel2;
	public javax.swing.JPanel jPanel3;
	public javax.swing.JPanel jPanel4;
	public javax.swing.JProgressBar jProgressBar;
	public javax.swing.JProgressBar jProgressBar1;
	public javax.swing.JProgressBar jProgressBar10;
	public javax.swing.JProgressBar jProgressBar11;
	public javax.swing.JProgressBar jProgressBar12;
	public javax.swing.JProgressBar jProgressBar13;
	public javax.swing.JProgressBar jProgressBar14;
	public javax.swing.JProgressBar jProgressBar15;
	public javax.swing.JProgressBar jProgressBar16;
	public javax.swing.JProgressBar jProgressBar17;
	public javax.swing.JProgressBar jProgressBar18;
	public javax.swing.JProgressBar jProgressBar19;
	public javax.swing.JProgressBar jProgressBar2;
	public javax.swing.JProgressBar jProgressBar20;
	public javax.swing.JProgressBar jProgressBar21;
	public javax.swing.JProgressBar jProgressBar22;
	public javax.swing.JProgressBar jProgressBar23;
	public javax.swing.JProgressBar jProgressBar24;
	public javax.swing.JProgressBar jProgressBar25;
	public javax.swing.JProgressBar jProgressBar26;
	public javax.swing.JProgressBar jProgressBar27;
	public javax.swing.JProgressBar jProgressBar28;
	public javax.swing.JProgressBar jProgressBar29;
	public javax.swing.JProgressBar jProgressBar3;
	public javax.swing.JProgressBar jProgressBar4;
	public javax.swing.JProgressBar jProgressBar5;
	public javax.swing.JProgressBar jProgressBar6;
	public javax.swing.JProgressBar jProgressBar7;
	public javax.swing.JProgressBar jProgressBar8;
	public javax.swing.JProgressBar jProgressBar9;
	public javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration
}
