/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cclip.gui.geo.cadastre;

import com.cclip.gui.util.JPanelForm;

/**
 *
 * @author java
 */
public class JPanelCadastreView extends JPanelForm {

    /**
     * Creates new form JPanelCadastre
     */
    public JPanelCadastreView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelCadastralCode = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabelUfId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelCtaCli = new javax.swing.JLabel();
        jLabelCityArea = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelSubCtaCli = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelDv = new javax.swing.JLabel();
        jPanelGeneral = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabelCadastreType = new javax.swing.JLabel();
        jLabelCadastreSituation = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabelWaterMeter = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabelDateCreate = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabelDateDelete = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelReasonLow = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        jLabelM2 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabelM2Covered = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabelM2CoveredBlock = new javax.swing.JLabel();
        jLabelM2Percent = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabelM2CoveredShared = new javax.swing.JLabel();
        jLabelM2SharedPercent = new javax.swing.JLabel();
        jLabelM2CoveredPh = new javax.swing.JLabel();
        jLabelM2PHPercent = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabelM2CoveredTotal = new javax.swing.JLabel();
        jLabelM2PercentTotal = new javax.swing.JLabel();
        jPanelUfDesc = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneUfDesc = new javax.swing.JTextPane();
        jPanelAudit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelAuditVersion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelAuditVersionCodeLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelAuditVersionLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelAuditDateCreate = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelAuditUserCreate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabelAuditDateUpdate = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelAuditUserUpdate = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPaneId = new javax.swing.JTextPane();
        jPanelPh = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePhList = new javax.swing.JTable();
        jLabel62 = new javax.swing.JLabel();
        jLabelCantPhCalc = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabelCadastreSubDivisionType = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabelCadastreActivityType = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableBlockPhList = new javax.swing.JTable();
        jLabelCantPh = new javax.swing.JLabel();
        jPanelBlock = new javax.swing.JPanel();
        jScrollPaneCadastreBlockList = new javax.swing.JScrollPane();
        jTableBlockList = new javax.swing.JTable();
        jPanelUserWaterDesc = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPaneUserWaterDesc = new javax.swing.JTextPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableScanningList = new javax.swing.JTable();
        jLabelCr2 = new javax.swing.JLabel();
        jLabelCr1 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabelCr0 = new javax.swing.JLabel();
        jLabelDateScanning2 = new javax.swing.JLabel();
        jLabelDateScanning1 = new javax.swing.JLabel();
        jLabelDateScanning0 = new javax.swing.JLabel();
        jPanelInmAddres = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneInmAddres = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelCadastralCode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCadastralCode.setText("DD-ZZ-MMM-PPP-ppp");

        jLabel111.setForeground(new java.awt.Color(0, 102, 153));
        jLabel111.setText("UF:");

        jLabelUfId.setText("000000");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Cta Cli:");

        jLabelCtaCli.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCtaCli.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCtaCli.setText("000000");

        jLabelCityArea.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCityArea.setText("(322) Norte");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(0, 102, 153));
        jLabel15.setText("Sub Cta:");

        jLabelSubCtaCli.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSubCtaCli.setText("000000000000");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("DV:");

        jLabelDv.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelDv.setText("76");

        jPanelGeneral.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Características Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelGeneral.setForeground(new java.awt.Color(0, 102, 153));

        jLabel57.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 102, 153));
        jLabel57.setText("Tipo:");

        jLabel71.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 102, 153));
        jLabel71.setText("Situación:");

        jLabelCadastreType.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCadastreType.setText("(PH) Propiedad Horizontal");

        jLabelCadastreSituation.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCadastreSituation.setText("(OP) Obra Parcial");

        jLabel107.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(0, 102, 153));
        jLabel107.setText("Posee Medidor:");

        jLabelWaterMeter.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelWaterMeter.setText("Si");

        jLabel101.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(0, 102, 153));
        jLabel101.setText("Alta:");

        jLabelDateCreate.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelDateCreate.setText("01/01/1989");

        jLabel103.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(0, 102, 153));
        jLabel103.setText("Fecha Baja:");

        jLabelDateDelete.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelDateDelete.setForeground(new java.awt.Color(153, 0, 0));
        jLabelDateDelete.setText("01/01/1987");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Motivo Baja:");

        jLabelReasonLow.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelReasonLow.setForeground(new java.awt.Color(153, 0, 51));
        jLabelReasonLow.setText("(xxxxx) xxxxxxxxxxxxxxxxxxxxxxxxxx");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel107, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel101, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel103, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelReasonLow)
                    .addComponent(jLabelDateDelete)
                    .addComponent(jLabelDateCreate)
                    .addComponent(jLabelCadastreType)
                    .addComponent(jLabelCadastreSituation)
                    .addComponent(jLabelWaterMeter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastreType)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(jLabelCadastreSituation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWaterMeter)
                    .addComponent(jLabel107))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel101)
                    .addComponent(jLabelDateCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel103)
                    .addComponent(jLabelDateDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelReasonLow))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Metros Cuadrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 102, 153));

        jLabel97.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(0, 102, 153));
        jLabel97.setText("Terreno:");

        jLabelM2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2.setText("328");

        jLabel99.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(0, 102, 153));
        jLabel99.setText("Cubiertos:");

        jLabelM2Covered.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2Covered.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2Covered.setText("140");

        jLabel100.setBackground(new java.awt.Color(255, 255, 102));
        jLabel100.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(0, 102, 153));
        jLabel100.setText("Bloques:");

        jLabelM2CoveredBlock.setBackground(new java.awt.Color(255, 255, 102));
        jLabelM2CoveredBlock.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2CoveredBlock.setForeground(new java.awt.Color(0, 102, 153));
        jLabelM2CoveredBlock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2CoveredBlock.setText("140");

        jLabelM2Percent.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2Percent.setForeground(new java.awt.Color(0, 102, 153));
        jLabelM2Percent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2Percent.setText("140%");

        jLabel119.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(0, 102, 153));
        jLabel119.setText("Compartidos:");

        jLabelM2CoveredShared.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2CoveredShared.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2CoveredShared.setText("140");

        jLabelM2SharedPercent.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2SharedPercent.setForeground(new java.awt.Color(0, 102, 153));
        jLabelM2SharedPercent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2SharedPercent.setText("140%");

        jLabelM2CoveredPh.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2CoveredPh.setForeground(new java.awt.Color(0, 102, 153));
        jLabelM2CoveredPh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2CoveredPh.setText("140");

        jLabelM2PHPercent.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2PHPercent.setForeground(new java.awt.Color(0, 102, 153));
        jLabelM2PHPercent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2PHPercent.setText("140%");

        jLabel102.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(0, 102, 153));
        jLabel102.setText("PH's:");

        jLabel104.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(0, 102, 153));
        jLabel104.setText("PH's + Compartidos:");

        jLabelM2CoveredTotal.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2CoveredTotal.setForeground(new java.awt.Color(0, 102, 153));
        jLabelM2CoveredTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2CoveredTotal.setText("140");

        jLabelM2PercentTotal.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2PercentTotal.setForeground(new java.awt.Color(0, 102, 153));
        jLabelM2PercentTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2PercentTotal.setText("140%");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel97, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel99, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel119, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel102, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel104, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM2)
                    .addComponent(jLabelM2Covered)
                    .addComponent(jLabelM2CoveredShared)
                    .addComponent(jLabelM2CoveredPh)
                    .addComponent(jLabelM2CoveredTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM2Percent)
                    .addComponent(jLabelM2SharedPercent)
                    .addComponent(jLabelM2PHPercent)
                    .addComponent(jLabelM2PercentTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel100)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelM2CoveredBlock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel97)
                    .addComponent(jLabelM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel99)
                    .addComponent(jLabelM2Covered)
                    .addComponent(jLabelM2Percent)
                    .addComponent(jLabel100)
                    .addComponent(jLabelM2CoveredBlock))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM2SharedPercent)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel119)
                        .addComponent(jLabelM2CoveredShared)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM2PHPercent)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel102)
                        .addComponent(jLabelM2CoveredPh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM2PercentTotal)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel104)
                        .addComponent(jLabelM2CoveredTotal)))
                .addContainerGap())
        );

        jPanelUfDesc.setBackground(new java.awt.Color(255, 255, 255));
        jPanelUfDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Unidad de Facturación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelUfDesc.setForeground(new java.awt.Color(0, 102, 153));

        jScrollPane5.setBorder(null);

        jTextPaneUfDesc.setEditable(false);
        jTextPaneUfDesc.setBorder(null);
        jTextPaneUfDesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane5.setViewportView(jTextPaneUfDesc);

        javax.swing.GroupLayout jPanelUfDescLayout = new javax.swing.GroupLayout(jPanelUfDesc);
        jPanelUfDesc.setLayout(jPanelUfDescLayout);
        jPanelUfDescLayout.setHorizontalGroup(
            jPanelUfDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        jPanelUfDescLayout.setVerticalGroup(
            jPanelUfDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelAudit.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAudit.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Auditoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelAudit.setForeground(new java.awt.Color(0, 102, 153));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Versión:");

        jLabelAuditVersion.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabelAuditVersion.setText("jLabel2");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Código de Versión");

        jLabelAuditVersionCodeLabel.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabelAuditVersionCodeLabel.setText("jLabel4");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Etiqueta de Versión:");

        jLabelAuditVersionLabel.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabelAuditVersionLabel.setText("jLabel6");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Fecha de Creación:");

        jLabelAuditDateCreate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabelAuditDateCreate.setText("jLabel8");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("Usuario que Creó:");

        jLabelAuditUserCreate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabelAuditUserCreate.setText("jLabel10");

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setText("Fecha de Última Actualización:");

        jLabelAuditDateUpdate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabelAuditDateUpdate.setText("jLabel12");

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 153));
        jLabel26.setText("Último Usuario que Actualizó:");

        jLabelAuditUserUpdate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabelAuditUserUpdate.setText("jLabel14");

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 153));
        jLabel28.setText("Id:");

        jScrollPane9.setBorder(null);

        jTextPaneId.setEditable(false);
        jTextPaneId.setBorder(null);
        jTextPaneId.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jScrollPane9.setViewportView(jTextPaneId);

        javax.swing.GroupLayout jPanelAuditLayout = new javax.swing.GroupLayout(jPanelAudit);
        jPanelAudit.setLayout(jPanelAuditLayout);
        jPanelAuditLayout.setHorizontalGroup(
            jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuditLayout.createSequentialGroup()
                .addGroup(jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAuditLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuditVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuditVersionCodeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuditVersionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuditDateCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuditUserCreate))
                    .addGroup(jPanelAuditLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuditDateUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuditUserUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAuditLayout.setVerticalGroup(
            jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuditLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelAuditVersion)
                    .addComponent(jLabel9)
                    .addComponent(jLabelAuditVersionCodeLabel)
                    .addComponent(jLabel13)
                    .addComponent(jLabelAuditVersionLabel)
                    .addComponent(jLabel20)
                    .addComponent(jLabelAuditDateCreate)
                    .addComponent(jLabel22)
                    .addComponent(jLabelAuditUserCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addGroup(jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabelAuditDateUpdate)
                            .addComponent(jLabel26)
                            .addComponent(jLabelAuditUserUpdate)))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPh.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 10), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelPh.setForeground(new java.awt.Color(0, 102, 153));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTablePhList.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTablePhList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "ppp", "UF", "Cta.Cli.", "Piso", "Dto", "Calle", "N°", "Est.", "M2 Cub.", "%", "Tipo", "Actividad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablePhList);

        jLabel62.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 102, 153));
        jLabel62.setText("Total Unidades:");

        jLabelCantPhCalc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCantPhCalc.setForeground(new java.awt.Color(0, 102, 153));
        jLabelCantPhCalc.setText("999");

        jLabel58.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 102, 153));
        jLabel58.setText("Tipo sub. Cta. Madre:");

        jLabelCadastreSubDivisionType.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCadastreSubDivisionType.setText("(PH) Propiedad Horizontal");

        jLabel72.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 102, 153));
        jLabel72.setText("Actividad Madre:");

        jLabelCadastreActivityType.setFont(new java.awt.Font("Abyssinica SIL", 0, 10)); // NOI18N
        jLabelCadastreActivityType.setText("(OP) Obra Parcial");

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));

        jTableBlockPhList.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTableBlockPhList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Año", "Mes", "Tipo", "M2", "Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTableBlockPhList);

        jLabelCantPh.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCantPh.setText("328");

        javax.swing.GroupLayout jPanelPhLayout = new javax.swing.GroupLayout(jPanelPh);
        jPanelPh.setLayout(jPanelPhLayout);
        jPanelPhLayout.setHorizontalGroup(
            jPanelPhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelPhLayout.createSequentialGroup()
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCadastreSubDivisionType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCadastreActivityType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCantPh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCantPhCalc)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPhLayout.setVerticalGroup(
            jPanelPhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhLayout.createSequentialGroup()
                .addGroup(jPanelPhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastreSubDivisionType)
                    .addComponent(jLabel58)
                    .addComponent(jLabel72)
                    .addComponent(jLabelCadastreActivityType)
                    .addComponent(jLabel62)
                    .addComponent(jLabelCantPhCalc)
                    .addComponent(jLabelCantPh))
                .addGap(11, 11, 11)
                .addGroup(jPanelPhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanelBlock.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBlock.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bloques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelBlock.setForeground(new java.awt.Color(0, 102, 153));

        jScrollPaneCadastreBlockList.setBackground(new java.awt.Color(255, 255, 255));

        jTableBlockList.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTableBlockList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Año", "Mes", "Tipo", "M2", "Destino", "Actividad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneCadastreBlockList.setViewportView(jTableBlockList);

        javax.swing.GroupLayout jPanelBlockLayout = new javax.swing.GroupLayout(jPanelBlock);
        jPanelBlock.setLayout(jPanelBlockLayout);
        jPanelBlockLayout.setHorizontalGroup(
            jPanelBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCadastreBlockList, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        jPanelBlockLayout.setVerticalGroup(
            jPanelBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCadastreBlockList, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );

        jPanelUserWaterDesc.setBackground(new java.awt.Color(255, 255, 255));
        jPanelUserWaterDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Usuario del Servicio de Agua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelUserWaterDesc.setForeground(new java.awt.Color(0, 102, 153));

        jScrollPane6.setBorder(null);

        jTextPaneUserWaterDesc.setEditable(false);
        jTextPaneUserWaterDesc.setBorder(null);
        jTextPaneUserWaterDesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane6.setViewportView(jTextPaneUserWaterDesc);

        javax.swing.GroupLayout jPanelUserWaterDescLayout = new javax.swing.GroupLayout(jPanelUserWaterDesc);
        jPanelUserWaterDesc.setLayout(jPanelUserWaterDescLayout);
        jPanelUserWaterDescLayout.setHorizontalGroup(
            jPanelUserWaterDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserWaterDescLayout.createSequentialGroup()
                .addComponent(jScrollPane6)
                .addGap(0, 0, 0))
        );
        jPanelUserWaterDescLayout.setVerticalGroup(
            jPanelUserWaterDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Barridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel12.setForeground(new java.awt.Color(0, 102, 153));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        jTableScanningList.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTableScanningList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Código", "Sup.", "% Av.", "Censista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableScanningList);

        jLabelCr2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCr2.setText("jLabel1");

        jLabelCr1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCr1.setText("jLabel1");

        jLabel61.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 102, 153));
        jLabel61.setText("3 Ultimos:");

        jLabelCr0.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelCr0.setText("jLabel1");

        jLabelDateScanning2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelDateScanning2.setText("jLabel1");

        jLabelDateScanning1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelDateScanning1.setText("jLabel3");

        jLabelDateScanning0.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelDateScanning0.setText("jLabel4");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCr0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDateScanning0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDateScanning1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCr2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDateScanning2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabelCr0)
                    .addComponent(jLabelDateScanning0)
                    .addComponent(jLabelCr1)
                    .addComponent(jLabelDateScanning1)
                    .addComponent(jLabelCr2)
                    .addComponent(jLabelDateScanning2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        jPanelInmAddres.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInmAddres.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Domicilio del Inmueble", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelInmAddres.setForeground(new java.awt.Color(0, 102, 153));

        jScrollPane7.setBorder(null);

        jTextPaneInmAddres.setEditable(false);
        jTextPaneInmAddres.setBorder(null);
        jTextPaneInmAddres.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextPaneInmAddres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPaneInmAddresMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTextPaneInmAddres);

        javax.swing.GroupLayout jPanelInmAddresLayout = new javax.swing.GroupLayout(jPanelInmAddres);
        jPanelInmAddres.setLayout(jPanelInmAddresLayout);
        jPanelInmAddresLayout.setHorizontalGroup(
            jPanelInmAddresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        jPanelInmAddresLayout.setVerticalGroup(
            jPanelInmAddresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAudit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCadastralCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel111)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUfId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCtaCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCityArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSubCtaCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDv)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanelPh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInmAddres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelUfDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelUserWaterDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastralCode)
                    .addComponent(jLabel111)
                    .addComponent(jLabelUfId)
                    .addComponent(jLabel11)
                    .addComponent(jLabelCtaCli)
                    .addComponent(jLabelCityArea)
                    .addComponent(jLabel15)
                    .addComponent(jLabelSubCtaCli)
                    .addComponent(jLabel17)
                    .addComponent(jLabelDv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInmAddres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelUfDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelUserWaterDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAudit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                        

    private void jTextPaneInmAddresMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
    }                                               


    // Variables declaration - do not modify                     
    protected javax.swing.JLabel jLabel100;
    protected javax.swing.JLabel jLabel101;
    protected javax.swing.JLabel jLabel102;
    protected javax.swing.JLabel jLabel103;
    protected javax.swing.JLabel jLabel104;
    protected javax.swing.JLabel jLabel107;
    protected javax.swing.JLabel jLabel11;
    protected javax.swing.JLabel jLabel111;
    protected javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel13;
    protected javax.swing.JLabel jLabel15;
    protected javax.swing.JLabel jLabel17;
    protected javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    protected javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    protected javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JLabel jLabel97;
    protected javax.swing.JLabel jLabel99;
    protected javax.swing.JLabel jLabelAuditDateCreate;
    protected javax.swing.JLabel jLabelAuditDateUpdate;
    protected javax.swing.JLabel jLabelAuditUserCreate;
    protected javax.swing.JLabel jLabelAuditUserUpdate;
    protected javax.swing.JLabel jLabelAuditVersion;
    protected javax.swing.JLabel jLabelAuditVersionCodeLabel;
    protected javax.swing.JLabel jLabelAuditVersionLabel;
    protected javax.swing.JLabel jLabelCadastralCode;
    protected javax.swing.JLabel jLabelCadastreActivityType;
    protected javax.swing.JLabel jLabelCadastreSituation;
    protected javax.swing.JLabel jLabelCadastreSubDivisionType;
    protected javax.swing.JLabel jLabelCadastreType;
    protected javax.swing.JLabel jLabelCantPh;
    protected javax.swing.JLabel jLabelCantPhCalc;
    protected javax.swing.JLabel jLabelCityArea;
    protected javax.swing.JLabel jLabelCr0;
    protected javax.swing.JLabel jLabelCr1;
    protected javax.swing.JLabel jLabelCr2;
    protected javax.swing.JLabel jLabelCtaCli;
    protected javax.swing.JLabel jLabelDateCreate;
    protected javax.swing.JLabel jLabelDateDelete;
    protected javax.swing.JLabel jLabelDateScanning0;
    protected javax.swing.JLabel jLabelDateScanning1;
    protected javax.swing.JLabel jLabelDateScanning2;
    protected javax.swing.JLabel jLabelDv;
    protected javax.swing.JLabel jLabelM2;
    protected javax.swing.JLabel jLabelM2Covered;
    protected javax.swing.JLabel jLabelM2CoveredBlock;
    protected javax.swing.JLabel jLabelM2CoveredPh;
    protected javax.swing.JLabel jLabelM2CoveredShared;
    protected javax.swing.JLabel jLabelM2CoveredTotal;
    protected javax.swing.JLabel jLabelM2PHPercent;
    protected javax.swing.JLabel jLabelM2Percent;
    protected javax.swing.JLabel jLabelM2PercentTotal;
    protected javax.swing.JLabel jLabelM2SharedPercent;
    protected javax.swing.JLabel jLabelReasonLow;
    protected javax.swing.JLabel jLabelSubCtaCli;
    protected javax.swing.JLabel jLabelUfId;
    protected javax.swing.JLabel jLabelWaterMeter;
    protected javax.swing.JPanel jPanel12;
    protected javax.swing.JPanel jPanel6;
    protected javax.swing.JPanel jPanelAudit;
    protected javax.swing.JPanel jPanelBlock;
    protected javax.swing.JPanel jPanelGeneral;
    protected javax.swing.JPanel jPanelInmAddres;
    protected javax.swing.JPanel jPanelPh;
    protected javax.swing.JPanel jPanelUfDesc;
    protected javax.swing.JPanel jPanelUserWaterDesc;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPaneCadastreBlockList;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    protected javax.swing.JTable jTableBlockList;
    protected javax.swing.JTable jTableBlockPhList;
    protected javax.swing.JTable jTablePhList;
    protected javax.swing.JTable jTableScanningList;
    protected javax.swing.JTextPane jTextPaneId;
    protected javax.swing.JTextPane jTextPaneInmAddres;
    protected javax.swing.JTextPane jTextPaneUfDesc;
    protected javax.swing.JTextPane jTextPaneUserWaterDesc;
    // End of variables declaration                   
}
