/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cclip.gui.schedule.census;

import com.cclip.gui.util.JPanelForm;

/**
 *
 * @author java
 */
public class JPanelCensusView extends JPanelForm {

    /**
     * Creates new form JPanelCensusView
     */
    public JPanelCensusView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanelView = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelType = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelNumberCensus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSchedule = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        jLabelCensused = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelScheduleBatch = new javax.swing.JLabel();
        jPanelGeneralBuildong = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabelM2ShedsGeneral = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelM2GeneralBuilding = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelM2BuildingsPublicEntertainment = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabelM2ProgressConstruction = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelCensusTaker = new javax.swing.JLabel();
        jPanelCadastreView = new com.cclip.gui.geo.cadastre.JPanelCadastreViewCustomW();
        jPanelFooter = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabelCensusPerson = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneComment = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabelSigned = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 96, 145));

        jPanelView.setBackground(new java.awt.Color(255, 255, 255));

        jPanelHeader.setBackground(new java.awt.Color(55, 96, 145));
        jPanelHeader.setForeground(new java.awt.Color(0, 102, 153));

        jLabelType.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(255, 255, 255));
        jLabelType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelType.setText("M");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("N°:");

        jLabelNumberCensus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelNumberCensus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumberCensus.setText("n°");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cronograma (Año):");

        jLabelSchedule.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSchedule.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSchedule.setText("jLabel2");

        jLabelResult.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelResult.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResult.setText("Resultado");

        jLabelCensused.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCensused.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCensused.setText("dd/MM/YYYY");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lote:");

        jLabelScheduleBatch.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelScheduleBatch.setForeground(new java.awt.Color(255, 255, 255));
        jLabelScheduleBatch.setText("jLabel2");

        jPanelGeneralBuildong.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGeneralBuildong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Obras en Construcción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 0, 8), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanelGeneralBuildong.setForeground(new java.awt.Color(0, 102, 153));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("Galpones en General:");

        jLabelM2ShedsGeneral.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2ShedsGeneral.setText("jLabel18");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setText("Edificios en General:");

        jLabelM2GeneralBuilding.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2GeneralBuilding.setText("jLabel24");

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 153));
        jLabel26.setText("Edificios para Espectaculos Publicos:");

        jLabelM2BuildingsPublicEntertainment.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2BuildingsPublicEntertainment.setText("jLabel35");

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 153));
        jLabel36.setText("Progreso de Construcción:");

        jLabelM2ProgressConstruction.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelM2ProgressConstruction.setText("jLabel37");

        javax.swing.GroupLayout jPanelGeneralBuildongLayout = new javax.swing.GroupLayout(jPanelGeneralBuildong);
        jPanelGeneralBuildong.setLayout(jPanelGeneralBuildongLayout);
        jPanelGeneralBuildongLayout.setHorizontalGroup(
            jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralBuildongLayout.createSequentialGroup()
                .addGroup(jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM2ShedsGeneral)
                    .addComponent(jLabelM2BuildingsPublicEntertainment))
                .addGap(37, 37, 37)
                .addGroup(jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelM2GeneralBuilding)
                    .addComponent(jLabelM2ProgressConstruction))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGeneralBuildongLayout.setVerticalGroup(
            jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralBuildongLayout.createSequentialGroup()
                .addGroup(jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelM2ShedsGeneral)
                    .addComponent(jLabel23)
                    .addComponent(jLabelM2GeneralBuilding))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralBuildongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabelM2BuildingsPublicEntertainment)
                    .addComponent(jLabelM2ProgressConstruction)
                    .addComponent(jLabel36))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Censista:");

        jLabelCensusTaker.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCensusTaker.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCensusTaker.setText("jLabel2");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabelCensused)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNumberCensus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelResult))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelScheduleBatch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCensusTaker)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGeneralBuildong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabelNumberCensus)
                    .addComponent(jLabel1)
                    .addComponent(jLabelSchedule)
                    .addComponent(jLabelCensused)
                    .addComponent(jLabelResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabelScheduleBatch)
                    .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabelCensusTaker)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelGeneralBuildong, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanelFooter.setBackground(new java.awt.Color(55, 96, 145));
        jPanelFooter.setForeground(new java.awt.Color(0, 102, 153));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Encuestado");

        jLabelCensusPerson.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCensusPerson.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCensusPerson.setText("(27656133) Diego Pablo Mansilla");

        jScrollPane7.setBackground(new java.awt.Color(55, 96, 146));
        jScrollPane7.setBorder(null);

        jTextPaneComment.setEditable(false);
        jTextPaneComment.setBackground(new java.awt.Color(55, 96, 145));
        jTextPaneComment.setBorder(null);
        jTextPaneComment.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextPaneComment.setForeground(new java.awt.Color(255, 255, 255));
        jTextPaneComment.setText("Comentarios");
        jScrollPane7.setViewportView(jTextPaneComment);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Firmado:");

        jLabelSigned.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSigned.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSigned.setText("Si");

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addComponent(jLabelCensusPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSigned)
                        .addContainerGap())
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFooterLayout.createSequentialGroup()
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7))
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCensusPerson)
                            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel3)
                                .addComponent(jLabelSigned)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCadastreView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelViewLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelCadastreView, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel7;
    protected javax.swing.JLabel jLabelCensusPerson;
    protected javax.swing.JLabel jLabelCensusTaker;
    protected javax.swing.JLabel jLabelCensused;
    protected javax.swing.JLabel jLabelM2BuildingsPublicEntertainment;
    protected javax.swing.JLabel jLabelM2GeneralBuilding;
    protected javax.swing.JLabel jLabelM2ProgressConstruction;
    protected javax.swing.JLabel jLabelM2ShedsGeneral;
    protected javax.swing.JLabel jLabelNumberCensus;
    protected javax.swing.JLabel jLabelResult;
    protected javax.swing.JLabel jLabelSchedule;
    protected javax.swing.JLabel jLabelScheduleBatch;
    protected javax.swing.JLabel jLabelSigned;
    protected javax.swing.JLabel jLabelType;
    public com.cclip.gui.geo.cadastre.JPanelCadastreViewCustomW jPanelCadastreView;
    protected javax.swing.JPanel jPanelFooter;
    protected javax.swing.JPanel jPanelGeneralBuildong;
    protected javax.swing.JPanel jPanelHeader;
    protected javax.swing.JPanel jPanelView;
    private javax.swing.JScrollPane jScrollPane7;
    protected javax.swing.JTextPane jTextPaneComment;
    // End of variables declaration                   
}
